---
version: '3.3'

services:
  traefik:
    image: docker.io/library/traefik:v3.4.0
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # --> (Optional) Enable Dashboard, don't do in production
      - 8080:8080
      # <--
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./config/traefik/:/etc/traefik/:ro
      - ./certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}  # <-- Change this to your Cloudflare API Token
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true  # <-- (Optional) Change this to false if you want to create a new network